export const metadata = {
  title: 'Lanceiros MG | Register',
  description: 'Generated by create next app',
}

export default function Register() {
  return (
    <main>
      <h1>Register</h1>
    </main>
  )
}
