export const metadata = {
  title: 'Lanceiros MG | Login',
  description: 'Generated by create next app',
}

export default function Login() {
  return (
    <main>
      <h1>Login</h1>
    </main>
  )
}
